# Run from this directory:
#   cd services/symflow-api
#   cargo install --force cargo-make
#   cargo make api-dev
#
# Useful tasks:
#   cargo make api-dev   # Run symflow-api locally with cargo.

[config]
default_to_workspace = false

[tasks.api-dev]
description = "Run symflow-api locally with cargo."
script = '''
set -eu

DATABASE_URL="${SYMFLOW_API_DEV_DATABASE_URL:-postgres://${POSTGRES_USER:-symflow}:${POSTGRES_PASSWORD:-symflow}@127.0.0.1:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-symflow}?sslmode=disable}"
SYMFLOW_API_ADDR="${SYMFLOW_API_DEV_ADDR:-127.0.0.1:8787}"
RUST_LOG="${RUST_LOG:-info}"

export DATABASE_URL
export SYMFLOW_API_ADDR
export RUST_LOG

cargo run --bin symflow-api
'''
